### PR TITLE
Automatic mirroring of Common.css

### PR DESCRIPTION
**Pull request by headquarter8302**
Using GitHub Actions, we can fetch data from the wiki from any URL and then commit it to the Common.css file we have. Essentially having a working automatic mirror.

The current action is as follows:

1. Runs at 0:00 UTC every day or be dispatched manually (the most amount of time a GH Action can be automatically triggered is every 5 minutes).
2. Checks out the repo.
3. Sets the git user as myself, will change it to the user `actions` if PR passes.
4. Fetches plaintext from https://youtube.fandom.com/wiki/MediaWiki:Common.css?action=raw.
5. Commit it to main.

### CODE REVIEW

**Comment by Saurmandal** [comment]
As someone who knows nothing about auto mirroring, this is pretty cool.

**Comment by headquarter8302** [comment]
Should we implement this?

**Comment by headquarter8302** [comment]
It should also be noted that the Action fails when the main branch is equal to the fetched revision

**Comment by headquarter8302** [comment]
Action now handles errors gracefully. @Saurmandal merge?

**Pull request merged**
